server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Auth microservice
    location /auth/ {
        proxy_pass         http://auth-api:8001/auth/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    # Main product API
    location /api/ {
        proxy_pass         http://product-api:8080/api/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    # Media files (uploaded images served by product API)
    location /media/ {
        proxy_pass         http://product-api:8080/media/;
        proxy_set_header   Host              $host;
    }

    # Static frontend — everything else
    location / {
        try_files $uri $uri/ /index.html;
    }
}
